name:               "//blog/"

# URL
baseurl:            "/blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "Home"
    href:           "//arunraj.xyz"
  - name:           "Download this template"
    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
