# Site settings
title: theblueasterisk
email: arunrajrs92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stuff that i find interesting
meta_description: "web log of arun"
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://blueasterisk.github.io" # the base hostname & protocol for your site
twitter_username: _raj9
github_username:  blueasterisk

# Build settings
markdown: kramdown
